export const AUTHOR_SLUG_FETCH_REQUEST = 'AUTHOR_SLUG_FETCH_REQUEST';
export const AUTHOR_SLUG_FETCH_SUCCESS = 'AUTHOR_SLUG_FETCH_SUCCESS';
export const AUTHOR_SLUG_FETCH_FAIL = 'AUTHOR_SLUG_FETCH_FAIL';

export const AUTHOR_NAME_FETCH_REQUEST = 'AUTHOR_NAME_FETCH_REQUEST';
export const AUTHOR_NAME_FETCH_SUCCESS = 'AUTHOR_NAME_FETCH_SUCCESS';
export const AUTHOR_NAME_FETCH_FAIL = 'AUTHOR_NAME_FETCH_FAIL';

export const AUTHOR_ID_FETCH_REQUEST = 'AUTHOR_ID_FETCH_REQUEST';
export const AUTHOR_ID_FETCH_SUCCESS = 'AUTHOR_ID_FETCH_SUCCESS';
export const AUTHOR_ID_FETCH_FAIL = 'AUTHOR_ID_FETCH_FAIL';
