// get single post
export const POST_FETCH_REQUEST = 'POST_FETCH_REQUEST';
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS';
export const POST_FETCH_FAIL = 'POST_FETCH_FAIL';

// get all posts
export const POSTS_FETCH_REQUEST = 'POSTS_FETCH_REQUEST';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_FETCH_FAIL = 'POSTS_FETCH_FAIL';
export const POSTS_FETCH_RESET = 'POSTS_FETCH_RESET';

// get recent posts
export const POSTS_FETCH_RECENT_REQUEST = 'POSTS_FETCH_RECENT_REQUEST';
export const POSTS_FETCH_RECENT_SUCCESS = 'POSTS_FETCH_RECENT_SUCCESS';
export const POSTS_FETCH_RECENT_FAIL = 'POSTS_FETCH_RECENT_FAIL';

// get posts by author
export const POSTS_FETCH_AUTHOR_REQUEST = 'POSTS_FETCH_AUTHOR_REQUEST';
export const POSTS_FETCH_AUTHOR_SUCCESS = 'POSTS_FETCH_AUTHOR_SUCCESS';
export const POSTS_FETCH_AUTHOR_FAIL = 'POSTS_FETCH_AUTHOR_FAIL';

// get posts by category
export const POSTS_CATEGORY_FETCH_REQUEST = 'POSTS_CATEGORY_FETCH_REQUEST';
export const POSTS_CATEGORY_FETCH_SUCCESS = 'POSTS_CATEGORY_FETCH_SUCCESS';
export const POSTS_CATEGORY_FETCH_FAIL = 'POSTS_CATEGORY_FETCH_FAIL';

// get posts by search
export const POSTS_SEARCH_FETCH_REQUEST = 'POSTS_SEARCH_FETCH_REQUEST';
export const POSTS_SEARCH_FETCH_SUCCESS = 'POSTS_SEARCH_FETCH_SUCCESS';
export const POSTS_SEARCH_FETCH_FAIL = 'POSTS_SEARCH_FETCH_FAIL';
